service: slack-app
provider:
  name: aws
  runtine: nodejs12.x
  region: eu-west-2
  role: arn:aws:iam::211791358895:role/slack
  timeout: 5
  stage: ${opt:stage, 'dev'}
  memorySize: 128
functions:
  dispatcher:
    handler: bot.run
    description: description
    exclude:
      - package-lock.json
    optimize: true
    events:
      - http:
          path: "/events"
          method: post 